# Generated by Django 5.0.1 on 2024-01-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='cpf',
            new_name='cpf_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='id',
            new_name='id_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome',
            new_name='nome_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='telefone',
            new_name='telefone_funcionario',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='id',
            new_name='id_ingrediente',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='nome',
            new_name='nome_ingrediente',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='unidadeMedida',
            new_name='unidade_Medida',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id',
            new_name='id_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='valor',
            new_name='valor_final',
        ),
        migrations.RenameField(
            model_name='pedidoproduto',
            old_name='quantidade',
            new_name='quantidade_comprada',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id',
            new_name='id_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='produtoingrediente',
            old_name='quantidade',
            new_name='quantidade_usada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora',
        ),
    ]
