# Generated by Django 5.0.1 on 2024-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_remove_funcionario_cpf_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('doce', 'Doce'), ('salgado', 'Salgado'), ('bebida', 'Bebida'), ('bolo', 'Bolo')], default='salgado', max_length=15),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='gerenciamento/img/'),
        ),
    ]
