# Generated by Django 5.0.1 on 2024-01-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0009_alter_pedido_data_alter_pedido_valor_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='completo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
