# Generated by Django 5.0.1 on 2024-02-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0012_avaliacao_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='quantidade_usada',
        ),
    ]
